// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgtezttjspmfvvftvjbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRndGV6dHRqc3BtZnZ2ZnR2amJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTk0OTYsImV4cCI6MjA3NDY3NTQ5Nn0.j4oU71VcXgQTTNgzWbgtipGdwXvsuqQimYvEA2O-wZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});